### ISSUE TITLE
batch_labels = int(m.group("batch_labels").replace(",", "")) error NoneType object has no attribute replace

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-tensorboard#12]
Hi,

It seems like the marian-tensorboard assumes `batch_labels` will be present in the log file, but they if they are not (and they are not enabled by default), then we have a crash:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dheart/uni_stuff/postdoc/empty-train-dissect/.env/lib/python3.10/site-packages/marian_tensorboard/marian_tensorboard.py", line 392, in run
    for log_tuple in parser.parse_line(line):
  File "/home/dheart/uni_stuff/postdoc/empty-train-dissect/.env/lib/python3.10/site-packages/marian_tensorboard/marian_tensorboard.py", line 176, in parse_line
    batch_labels = int(m.group("batch_labels").replace(",", ""))
AttributeError: 'NoneType' object has no attribute 'replace'
```

I am using the default settings + lr logging and here's how my log files look like typically:

```
[2023-02-28 11:09:14] [memory] Reserving 115 MB, device gpu3
[2023-02-28 11:19:28] Ep. 1 : Up. 1000 : Sen. 1,145,978 : Cost 8.30549431 : Time 960.73s : 45194.29 words/s : gNorm 1.2744 : L.r. 1.8750e-05
[2023-02-28 11:29:43] Ep. 1 : Up. 2000 : Sen. 2,384,310 : Cost 6.76088619 : Time 614.39s : 70635.68 words/s : gNorm 1.7251 : L.r. 3.7500e-05
[2023-02-28 11:39:56] Ep. 1 : Up. 3000 : Sen. 3,735,044 : Cost 5.96917725 : Time 612.94s : 69366.92 words/s : gNorm 1.7447 : L.r. 5.6250e-05
```
Seems like some fields should be optional, or?

**Comment by XapaJIaMnu** [comment]
Thanks @snukky , fixed
